import type { SkillDefinition, SkillFrontmatter } from './types.js';

const NATIVE_SKILL_VERSION = '2026.05.09';
const NATIVE_SKILL_SOURCE = 'native://claude-code-default';

interface NativeSkillSpec extends Partial<SkillFrontmatter> {
  name: string;
  description: string;
  body: string;
}

const nativeSkillSpecs: NativeSkillSpec[] = [
  {
    name: 'batch',
    description:
      'Plan and coordinate a large, parallelizable code change across isolated work units.',
    whenToUse:
      'Use when the user asks for a sweeping migration, refactor, rename, or multi-area implementation that can be split into independent units.',
    argumentHint: '<instruction>',
    tags: ['harness-native', 'developer-workflow', 'parallel-work'],
    allowedTools: ['read_file', 'grep', 'glob', 'bash', 'todo_write'],
    body: [
      '# Batch: Parallel Work Orchestration',
      '',
      'Use this skill when a change is too broad for a single linear edit pass and can be decomposed into independent, reviewable work units.',
      '',
      '## Goal',
      'Produce a researched plan, split the work into independent lanes, execute or delegate each lane safely, and verify the integrated result.',
      '',
      '## Workflow',
      '1. Inspect the repository first. Identify ownership boundaries, shared files, tests, build commands, and current dirty worktree changes.',
      '2. Decompose the requested change into independent units. Prefer per-module or per-directory slices. Keep shared-file edits in one lane.',
      '3. For each unit, define the file scope, expected behavior, and verification recipe.',
      '4. Use native subagents or isolated worktrees only when they are available and genuinely improve throughput. Each worker prompt must be self-contained and must warn that other workers may be editing nearby code.',
      '5. Integrate results in the main workspace. Do not revert unrelated user or worker edits.',
      '6. Run targeted tests first, then broader lint/typecheck/build checks as the risk warrants.',
      '',
      '## Worker Instructions Template',
      '- Stay inside the assigned file/module scope.',
      '- Do not rewrite the global plan or revert other workers changes.',
      '- Reuse existing patterns before adding abstractions.',
      '- Report changed files, tests run, failures, and unresolved risks.',
      '',
      '## Completion Criteria',
      '- Every unit has either landed or has a concrete blocker.',
      '- Shared integration points have been reviewed.',
      '- Verification evidence is fresh and cited in the final report.',
    ].join('\n'),
  },
  {
    name: 'claude-api',
    description:
      'Build or debug integrations that use the Claude API, Anthropic SDKs, or Claude Agent SDKs.',
    whenToUse:
      'Use when code imports Anthropic SDK packages or the user asks about Claude API, Messages API, tool use, streaming, prompt caching, batches, files, or the Claude Agent SDK.',
    tags: ['harness-native', 'anthropic', 'api', 'sdk'],
    allowedTools: ['read_file', 'grep', 'glob', 'web_fetch'],
    body: [
      '# Claude API Integration',
      '',
      'Use this skill for Claude API and Anthropic SDK implementation work.',
      '',
      '## Source Discipline',
      '- Check the local code first: package manager, SDK versions, existing client wrappers, environment variable names, and tests.',
      '- For API behavior, model ids, SDK signatures, pricing, limits, or current feature support, verify against official Anthropic documentation before making claims.',
      '- Do not apply Claude-specific guidance to OpenAI, OpenRouter, local, or unrelated AI SDK integrations unless the code clearly routes through Anthropic-compatible APIs.',
      '',
      '## Implementation Checklist',
      '1. Identify the language and SDK in use.',
      '2. Prefer the repository existing client and error-handling conventions.',
      '3. Keep secrets in environment/config paths already used by the project.',
      '4. Use structured outputs or tool calls only where the provider and client profile support them.',
      '5. For streaming, handle partial events, final usage, cancellation, and transport errors.',
      '6. For prompt caching, isolate stable prefixes and verify the provider supports the cache controls being used.',
      '7. Add targeted tests with mocked provider responses when live credentials are not available.',
      '',
      '## Common Pitfalls',
      '- Hard-coding stale model ids.',
      '- Assuming Messages API and OpenAI Chat Completions request shapes are interchangeable.',
      '- Dropping reasoning, tool-call, or usage metadata during response normalization.',
      '- Letting provider errors fall through as generic JSON parse failures.',
    ].join('\n'),
  },
  {
    name: 'claude-in-chrome',
    description:
      'Use browser automation for web-page interaction, screenshots, console inspection, and visual verification when browser tools are configured.',
    whenToUse:
      'Use when the user wants browser-based interaction, visual inspection, screenshots, console logs, or form automation and a compatible browser MCP/tool bridge is available.',
    tags: ['harness-native', 'browser', 'visual-verification'],
    allowedTools: ['tool_search', 'web_fetch'],
    body: [
      '# Claude in Chrome / Browser Automation',
      '',
      'This Harness-native version preserves the Claude Code browser-automation workflow, but it is conditional on browser tools actually being configured.',
      '',
      '## Before Acting',
      '1. Check whether browser automation tools are available through MCP or the current native agent surface.',
      '2. If no browser tools are available, use the nearest safe fallback: web fetch for static pages, Playwright or existing project test tooling for local apps, or explain the missing capability.',
      '3. Never claim that a page was clicked, viewed, or screenshotted unless the browser/tool output proves it.',
      '',
      '## Browser Workflow',
      '- Start by listing current tabs or opening the target URL.',
      '- Capture page state before making changes.',
      '- Prefer semantic locators and visible labels over brittle coordinates.',
      '- For UI verification, capture screenshots and check console/network errors.',
      '- For forms or external sites, avoid submission or irreversible actions unless the user explicitly requested that exact action.',
      '',
      '## Completion Criteria',
      '- The target page state is described from tool output.',
      '- Any interaction was confirmed by a changed page state, screenshot, console output, or network result.',
      '- Missing browser capability is reported as a verification gap.',
    ].join('\n'),
  },
  {
    name: 'debug',
    description:
      'Diagnose Harness CLI, provider, plugin, MCP, daemon, scheduler, or agent-loop issues.',
    whenToUse:
      'Use when the user reports a Harness session is failing, slow, misconfigured, blocked, or producing unexpected CLI/provider/tool behavior.',
    argumentHint: '[issue description]',
    tags: ['harness-native', 'debugging', 'diagnostics'],
    allowedTools: ['read_file', 'grep', 'glob', 'bash'],
    body: [
      '# Debug Harness',
      '',
      'Diagnose the current Harness issue without leaking secrets or disturbing unrelated work.',
      '',
      '## First Pass',
      '1. Restate the symptom and the command or workflow that failed.',
      '2. Check the current git status and avoid overwriting active edits.',
      '3. Inspect the relevant Harness surface: CLI command, provider profile, tool registry, plugin loader, MCP bridge, daemon, scheduler, or matter state.',
      '',
      '## Useful Local Checks',
      '- `npm run lint` for type-level failures.',
      '- `npm test -- <pattern>` for targeted Vitest runs.',
      '- `harness config show --json` for merged config. Redact secrets before reporting.',
      '- `harness provider show` and `harness control-panel status --json` for provider readiness.',
      '- `harness plugin list` and `harness mcp list --tools` for plugin/MCP discovery.',
      '- `harness daemon status` and `~/.atticus-harness/runtime/daemon.log` for background runs.',
      '- `harness events <matter> --tail 100` for matter-level run history.',
      '',
      '## Rules',
      '- Prefer evidence from logs, tests, and code over guesses.',
      '- Do not print API keys, OAuth tokens, secrets.env contents, or provider auth caches.',
      '- Do not kill processes, delete state, or reset git history unless the user explicitly requests it.',
      '- If the issue is a regression, isolate the failing behavior with the smallest test or reproduction before patching.',
      '',
      '## Output',
      'Lead with root cause when known, then the fix or next diagnostic step. Include commands run and any remaining verification gap.',
    ].join('\n'),
  },
  {
    name: 'keybindings-help',
    description:
      'Help modify Claude Code keybinding files safely when the user explicitly asks about Claude Code keyboard shortcuts.',
    whenToUse:
      'Use for Claude Code keybinding customization requests such as rebind keys, add chord shortcuts, or edit ~/.claude/keybindings.json.',
    tags: ['harness-native', 'claude-code', 'keybindings'],
    allowedTools: ['read_file', 'edit_file'],
    userInvocable: false,
    body: [
      '# Claude Code Keybindings Help',
      '',
      'Use this only for Claude Code keybinding configuration, not Harness CLI behavior.',
      '',
      '## Rules',
      '1. Read `~/.claude/keybindings.json` before editing. It may not exist.',
      '2. Merge changes with existing bindings. Do not replace the entire file.',
      '3. Include only contexts the user wants to change.',
      '4. Warn about terminal-reserved keys such as Ctrl+C, Ctrl+Z, Ctrl+D, Ctrl+S, Ctrl+Q, Ctrl+B for tmux, and Ctrl+A for screen.',
      '5. Use `null` to unbind a default key before adding a replacement if the user wants a full move rather than an additional binding.',
      '',
      '## Minimal File Shape',
      '{',
      '  "bindings": [',
      '    {',
      '      "context": "Chat",',
      '      "bindings": {',
      '        "ctrl+e": "chat:externalEditor"',
      '      }',
      '    }',
      '  ]',
      '}',
      '',
      'After editing, validate JSON syntax and tell the user exactly what changed.',
    ].join('\n'),
  },
  {
    name: 'loop',
    description:
      'Run a bounded repeat-until-done work loop for a local task, with checks between iterations.',
    whenToUse:
      'Use when the user asks to keep iterating, loop on tests, watch a condition in the current task, or continue until a clear local success condition is met.',
    argumentHint: '[condition or task]',
    tags: ['harness-native', 'iteration', 'verification'],
    allowedTools: ['read_file', 'grep', 'glob', 'bash', 'todo_write'],
    body: [
      '# Loop',
      '',
      'Use a bounded local loop. This is not a background scheduler; for later or recurring matter work, use the `schedule` skill and Harness scheduler commands.',
      '',
      '## Loop Contract',
      '1. Define the stop condition in one sentence.',
      '2. Define the smallest check that proves progress.',
      '3. Run one iteration: inspect, edit or act, verify.',
      '4. If verification fails, use the failure output to choose the next iteration.',
      '5. Stop when the success condition is met, when further iterations would be destructive or external, or when a blocker is proven.',
      '',
      '## Guardrails',
      '- Keep the loop finite. Use a practical retry cap for flaky or expensive checks.',
      '- Do not spin on commands with no new evidence.',
      '- Report the final evidence, not every intermediate attempt.',
    ].join('\n'),
  },
  {
    name: 'lorem-ipsum',
    description:
      'Generate approximate filler text for long-context or formatting tests.',
    whenToUse:
      'Use when the user needs placeholder prose or approximate token-volume filler for testing.',
    argumentHint: '[token_count]',
    tags: ['harness-native', 'testing', 'filler'],
    body: [
      '# Lorem Ipsum / Filler Text',
      '',
      'Generate plain filler text for testing context length, rendering, wrapping, or formatting.',
      '',
      '## Rules',
      '- If the user supplies a target token or word count, stay reasonably close and state that it is approximate.',
      '- Avoid using real personal data, real legal facts, or plausible citations.',
      '- For legal product tests, use clearly fake neutral placeholders rather than invented authorities.',
      '- Cap extremely large requests and explain the cap.',
    ].join('\n'),
  },
  {
    name: 'remember',
    description:
      'Review project and user memory layers and propose safe promotions or cleanup without applying them.',
    whenToUse:
      'Use when the user wants to review, organize, promote, or clean up AGENTS.md, local instructions, matter memory, or working notes.',
    tags: ['harness-native', 'memory', 'instructions'],
    allowedTools: ['read_file', 'grep', 'glob'],
    body: [
      '# Memory Review',
      '',
      'Review memory and instruction layers, then propose changes. Do not modify files unless the user explicitly asks for the edits.',
      '',
      '## Memory Layers',
      '- Repository instructions: `AGENTS.md` files in scope.',
      '- Project-local notes: `.omx/`, `.atticus/`, or documented project memory files when present.',
      '- Harness matter memory: matter state, case memory, accepted artifacts, events, and task records.',
      '- User-level configuration: `~/.atticus-harness/config.json` and related non-secret settings.',
      '',
      '## Classification',
      '- Promote to repo instructions only when the guidance is stable and applies to all future agents in this repo.',
      '- Keep user preferences out of committed project instructions unless they are team policy.',
      '- Keep temporary observations in working notes or matter memory.',
      '- Flag conflicts and outdated guidance with evidence.',
      '',
      '## Output',
      'Group proposals as promotions, cleanup, ambiguous items, and no-action-needed. Include file paths and rationale.',
    ].join('\n'),
  },
  {
    name: 'schedule',
    description:
      'Create, inspect, or delete Harness scheduled matter jobs and daemon-backed recurring runs.',
    whenToUse:
      'Use when the user wants a Harness matter prompt to run later, recur on a cron schedule, or be managed by the daemon scheduler.',
    argumentHint: '<matter> <cron> <prompt>',
    tags: ['harness-native', 'scheduler', 'daemon'],
    allowedTools: ['bash', 'read_file'],
    body: [
      '# Schedule Harness Jobs',
      '',
      'Use Harness scheduler commands for matter-scoped jobs.',
      '',
      '## Commands',
      '- Create: `harness schedule create <matter-name> --cron "0 9 * * *" --prompt "<prompt>" --recurring`.',
      '- List: `harness schedule list <matter-name>`.',
      '- Delete: `harness schedule delete <matter-name> <job-id>`.',
      '- Start daemon: `harness daemon start`.',
      '- Check daemon: `harness daemon status`.',
      '',
      '## Rules',
      '1. Confirm the matter exists before creating a job.',
      '2. Use five-field cron expressions.',
      '3. Include a self-contained prompt with matter name, desired output, and stop condition.',
      '4. Use recurring only when the user asked for repeated work.',
      '5. Do not schedule external sending, filing, or contact unless explicit operator authority exists.',
      '',
      '## Output',
      'Report the job id, cron expression, recurrence mode, daemon status, and any setup gap.',
    ].join('\n'),
  },
  {
    name: 'simplify',
    description:
      'Review changed code for reuse, quality, and efficiency, then apply small cleanup fixes.',
    whenToUse:
      'Use after implementing code changes, during cleanup/refactor work, or when the user asks to deslop or simplify a patch.',
    tags: ['harness-native', 'code-review', 'cleanup'],
    allowedTools: ['read_file', 'grep', 'glob', 'bash', 'edit_file'],
    body: [
      '# Simplify: Code Review and Cleanup',
      '',
      'Review the current changes for unnecessary complexity and fix issues that are clearly in scope.',
      '',
      '## Phase 1: Identify Changes',
      'Run `git diff` or inspect the files changed for the current task. If there are no git changes, review the files the user mentioned or the files edited in this session.',
      '',
      '## Phase 2: Review',
      'Check the patch from three angles:',
      '',
      '### Reuse',
      '- Look for existing utilities, helpers, constants, and patterns that should replace newly added logic.',
      '- Prefer deleting duplicate code over adding another abstraction.',
      '',
      '### Quality',
      '- Remove redundant state, parameter sprawl, copy-paste variants, leaky abstractions, stringly typed code, and comments that only narrate obvious behavior.',
      '- Keep public contracts and user-visible behavior unchanged unless the user asked for a behavior change.',
      '',
      '### Efficiency',
      '- Remove repeated file reads, duplicated network calls, avoidable sequential work, unbounded structures, and hot-path blocking work.',
      '- Add same-reference or no-change guards where update loops would otherwise notify downstream consumers unnecessarily.',
      '',
      '## Phase 3: Fix and Verify',
      'Apply only focused cleanup. Run targeted tests or typecheck after changes. If a finding is not worth fixing, mention it briefly instead of expanding the patch.',
    ].join('\n'),
  },
  {
    name: 'skillify',
    description:
      'Capture a repeatable workflow as a Harness SKILL.md file.',
    whenToUse:
      'Use when the user wants to turn a repeated process into a reusable Harness skill.',
    argumentHint: '[description of the process]',
    tags: ['harness-native', 'skill-authoring'],
    allowedTools: ['read_file', 'grep', 'glob', 'edit_file', 'bash'],
    body: [
      '# Skillify',
      '',
      'Create a reusable Harness skill from a repeatable process.',
      '',
      '## Analyze First',
      'Identify the process inputs, ordered steps, tools needed, success criteria, artifacts, user checkpoints, and common failure modes.',
      '',
      '## Harness Skill Shape',
      'Create `skills/<skill-name>/SKILL.md` with YAML frontmatter and a concise body.',
      '',
      'Recommended frontmatter fields:',
      '- `name`: stable kebab-case id.',
      '- `version`: date-like version such as `2026.05.09`.',
      '- `description`: one-line routing summary.',
      '- `task_types`: optional task categories.',
      '- `allowed-tools`: optional Harness tool names.',
      '- `tags`: optional routing tags.',
      '- `when_to_use`: detailed invocation guidance.',
      '- `argument-hint` and `arguments`: only when the skill needs parameters.',
      '- `context`: `fork` only for self-contained work that does not need mid-process user steering.',
      '',
      '## Body Requirements',
      '- State the goal and inputs.',
      '- Give concrete steps in order.',
      '- Add success criteria for each major step.',
      '- Include verification and stop conditions.',
      '- Call out destructive or external actions that require explicit user authority.',
      '',
      '## Save Rules',
      'Keep the skill small and specific. Do not add broad policy that belongs in AGENTS.md.',
    ].join('\n'),
  },
  {
    name: 'stuck',
    description:
      'Diagnose a frozen, slow, or stuck local Harness, Codex, Claude, Node, git, or test process without killing it.',
    whenToUse:
      'Use when the user says a local coding or Harness session is stuck, frozen, hanging, pegged, or very slow.',
    argumentHint: '[pid or symptom]',
    tags: ['harness-native', 'diagnostics', 'processes'],
    allowedTools: ['bash', 'read_file', 'grep'],
    body: [
      '# Stuck Process Diagnosis',
      '',
      'Investigate local stuck or slow sessions. Diagnostic only unless the user explicitly requests intervention.',
      '',
      '## What To Check',
      '- High CPU sustained across two samples.',
      '- Process state `D`, `T`, or `Z`.',
      '- Very high RSS or fast memory growth.',
      '- Hung child processes such as git, npm, node, tsc, vitest, or shell commands.',
      '- Harness daemon state in `~/.atticus-harness/runtime`.',
      '',
      '## Safe Commands',
      '- `ps -axo pid=,ppid=,pcpu=,rss=,etime=,state=,comm=,command=`',
      '- `pgrep -lP <pid>`',
      '- `harness daemon status`',
      '',
      '## Rules',
      '- Do not kill, signal, delete, or reset anything unless the user explicitly asks.',
      '- Exclude the current diagnostic process from findings.',
      '- If everything looks healthy, say so directly and do not invent a fault.',
      '',
      '## Output',
      'Report PID, CPU, RSS, state, uptime, command, child processes, likely diagnosis, and next safe action.',
    ].join('\n'),
  },
  {
    name: 'update-config',
    description:
      'Safely update Harness configuration, provider profiles, policy, plugin, MCP, or scheduler-related settings.',
    whenToUse:
      'Use when the user asks to configure Harness, providers, policies, plugins, MCP servers, search providers, secrets, or recurring behavior.',
    argumentHint: '[config request]',
    tags: ['harness-native', 'config', 'policy'],
    allowedTools: ['read_file', 'edit_file', 'bash'],
    body: [
      '# Update Harness Config',
      '',
      'Modify Harness configuration through CLI commands when possible, and direct JSON edits only when the CLI lacks the needed surface.',
      '',
      '## Prefer CLI Surfaces',
      '- `harness config show` and `harness config set <path> <value>` for global config.',
      '- `harness provider list`, `harness provider show`, and provider commands for model/provider profiles.',
      '- `harness policy show` and `harness policy preset <name>` for autonomy/tool policy.',
      '- `harness secrets set <KEY> <value>` for secrets. Do not print secret values back.',
      '- `harness plugin list` and `harness mcp list --tools` for plugin and MCP discovery checks.',
      '- `harness control-panel search ...` for legal search provider setup.',
      '',
      '## Direct Edit Rules',
      '1. Read the existing file first.',
      '2. Merge with existing objects and arrays. Do not replace unrelated settings.',
      '3. Preserve provider policy fail-closed behavior unless the user explicitly asked to change it.',
      '4. Keep secrets out of committed files and logs.',
      '5. Validate JSON and run targeted tests when config schema behavior changes.',
      '',
      '## Common Files',
      '- `~/.atticus-harness/config.json` for global settings.',
      '- `~/.atticus-harness/secrets.env` for secrets.',
      '- `matters/<matter>/_config.json` for matter overrides.',
      '- `matters/<matter>/_policy.json` for matter tool-policy overrides.',
      '',
      '## Output',
      'Summarize what changed, where it changed, and how it was verified.',
    ].join('\n'),
  },
  {
    name: 'verify',
    description:
      'Verify that a code, CLI, service, UI, or legal-output change actually works with fresh evidence.',
    whenToUse:
      'Use before claiming a change is complete, especially after code edits, CLI behavior changes, UI work, provider/tool changes, or legal draft promotion.',
    argumentHint: '[thing to verify]',
    tags: ['harness-native', 'verification', 'testing'],
    allowedTools: ['read_file', 'grep', 'glob', 'bash', 'web_fetch'],
    body: [
      '# Verify',
      '',
      'Prove the claim with the smallest validation that can actually fail for the relevant behavior.',
      '',
      '## Verification Plan',
      '1. State the claim being verified.',
      '2. Identify the changed behavior and the risk area.',
      '3. Choose the smallest meaningful check.',
      '4. Run it and read the output.',
      '5. If it fails, fix or narrow the claim. If it cannot run, explain the gap and run the next-best check.',
      '',
      '## Check Recipes',
      '- TypeScript/code: targeted Vitest test, then `npm run lint` or `npm run build` for shared type changes.',
      '- CLI: run the exact command or a dry-run/json equivalent against a fixture or temp matter.',
      '- Provider/tool bridge: mock the provider where possible and assert normalized request/response/tool metadata.',
      '- Daemon/scheduler: inspect created job records, daemon status, and event logs.',
      '- Web/server: start the dev server, hit the affected route with curl or browser tooling, and check logs.',
      '- Legal artifacts: use `harness verify`, `harness gate`, and `harness review` where applicable.',
      '',
      '## Output',
      'Report commands run, pass/fail result, relevant output lines, and remaining risk. Do not claim success without fresh evidence.',
    ].join('\n'),
  },
];

const nativeSkills = nativeSkillSpecs.map(createNativeSkill);

export function loadNativeSkillDefinitions(): SkillDefinition[] {
  return nativeSkills.map((skill) => ({
    ...skill,
    manifest: { ...skill.manifest },
    references: [...skill.references],
    examples: [...skill.examples],
  }));
}

export function mergeSkillDefinitions(groups: SkillDefinition[][]): SkillDefinition[] {
  const byId = new Map<string, SkillDefinition>();
  for (const group of groups) {
    for (const skill of group) {
      byId.set(skill.skillId, skill);
    }
  }
  return Array.from(byId.values());
}

function createNativeSkill(spec: NativeSkillSpec): SkillDefinition {
  const manifest: SkillFrontmatter = {
    name: spec.name,
    version: spec.version ?? NATIVE_SKILL_VERSION,
    description: spec.description,
    stage: spec.stage,
    taskTypes: spec.taskTypes,
    allowedTools: spec.allowedTools,
    tags: spec.tags,
    atticusRefined: spec.atticusRefined,
    jurisdictionFocus: spec.jurisdictionFocus,
    requiresLiveSourceVerification: spec.requiresLiveSourceVerification,
    externalActionMode: spec.externalActionMode,
    whenToUse: spec.whenToUse,
    argumentHint: spec.argumentHint,
    arguments: spec.arguments,
    userInvocable: spec.userInvocable,
    disableModelInvocation: spec.disableModelInvocation,
    context: spec.context,
    model: spec.model,
  };

  return {
    skillId: spec.name,
    path: `${NATIVE_SKILL_SOURCE}/${spec.name}`,
    manifest,
    body: spec.body.trim(),
    references: [],
    examples: [],
  };
}
